FROM ghcr.io/mooreryan/ocaml_alpine:4-14-2022-07-04-ebc03f8

# See https://wiki.alpinelinux.org/wiki/How_to_get_regular_stuff_working
RUN sudo apk add \
    util-linux \
    pciutils \
    usbutils \
    coreutils \
    binutils \
    findutils \
    grep \
    bash \
    bash-doc \
    bash-completion \
    perl
